MyPhotoSite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MyPhotoSite.views.home', name='home'),
    # url(r'^MyPhotoSite/', include('MyPhotoSite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^myphotos/', include('MyPhotos.urls', namespace="myphotos")),

    url(r'^accounts/', include('registration.backends.default.urls')),
    # url(r'^accounts/profile/$',TemplateView.as_view(template_name="myphotos/index.html")), # not needed because LOGIN_REDIRECT_URL in settings.py
)

MyPhotos/urls.py
__author__ = 'vijay'
from django.conf.urls import patterns, url, include
from django.conf import settings
from django.conf.urls.static import static

from MyPhotos import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^add/$', views.add_album, name='add_album'),
    url(r'^(?P<album_id>\d+)/photos/$', views.photos, name='photos'),
    url(r'^(?P<album_id>\d+)/photos/add/$', views.add_photo, name='add_photo'),
    url(r'^(?P<album_id>\d+)/photos/(?P<photo_id>\d+)/del/$', views.del_photo, name='del_photo'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyPhotos/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import time

# Create your models here.
# class User(models.Model):
#     username = models.CharField(max_length=80)
#     hash_pwd = models.CharField(max_length=64) # SHA-256 of password
#     email = models.CharField(max_length=80)
#     created_dt = models.DateTimeField(default=timezone.now())
#     modified_dt = models.DateTimeField(null=True)
#     verified = models.BooleanField(default=False) # indicates is user has confirmed registration or not
#     verify_code = models.CharField(max_length=255) # verification code to confirm registration
#     verified_dt = models.DateTimeField(null=True)
#
#     def __init__(self, *args, **kwargs):
#         super(User, self).__init__(*args, **kwargs)
#         self.modified_dt = timezone.now()
#
#     def __unicode__(self):
#         return self.username

class UserAlbum(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=80)
    created_dt = models.DateTimeField(default=timezone.now())
    modified_dt = models.DateTimeField(null=True)

    def __init__(self, *args, **kwargs):
        super(UserAlbum, self).__init__(*args, **kwargs)
        self.modified_dt = timezone.now()

    def __unicode__(self):
        return self.name + ' by ' + self.user.username

def uploadPath(instance, filename):
    return 'images/%s/%s/%s'%(instance.album.id,time.strftime('%Y/%m/%d', time.gmtime()),filename)

class AlbumPhoto(models.Model):
    album = models.ForeignKey(UserAlbum)
    filename = models.CharField(max_length=80)
    created_dt = models.DateTimeField(default=timezone.now())
    modified_dt = models.DateTimeField(null=True)
    tags = models.TextField(null=True, blank=True) # convert to JSONField later http://djangosnippets.org/snippets/377/
    imageFile = models.ImageField(upload_to=uploadPath)

    def __init__(self, *args, **kwargs):
        super(AlbumPhoto, self).__init__(*args, **kwargs)
        self.modified_dt = timezone.now()

    def __unicode__(self):
        return self.filename + ' in ' + self.album

    def delete(self, *args, **kwargs):
        # You have to prepare what you need before delete the model
        storage, path = self.imageFile.storage, self.imageFile.path
        # Delete the model before the file
        super(AlbumPhoto, self).delete(*args, **kwargs)
        # Delete the file after the model
        storage.delete(path)

MyPhotos/forms.py
__author__ = 'vijay'
from django import forms
from MyPhotos.models import AlbumPhoto

class PhotoUploadForm(forms.ModelForm):
    """Upload files with this form"""
    # def save(self, commit=True):
    #     instance = forms.ModelForm.save(self, commit=False)
    #     instance.filename = self.files['imageFile'].name
    #
    #     if commit:
    #         instance.save()
    #
    #     return instance
    class Meta:
        model = AlbumPhoto
        fields = ('imageFile','tags')

MyPhotos/views.py
from django.http import HttpResponse, HttpResponseRedirect
# from django.template import RequestContext, loader
# from django.http import Http404
from django.shortcuts import render, get_object_or_404, get_list_or_404

from django.contrib.auth.models import User
from MyPhotos.models import UserAlbum, AlbumPhoto
from MyPhotos.forms import PhotoUploadForm

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse

# def index(request):
#     user_list = User.objects.order_by('username')
#     # Approach 1
#     # output = ', '.join(str(u) for u in user_list) # join([str(u) for u in user_list]) # map(str, user_list)
#     # return HttpResponse(output)
#     # Approach 2
#     # template = loader.get_template('myphotos/index.html')
#     # context = RequestContext(request, {
#     #     'user_list':user_list,
#     # })
#     # return HttpResponse(template._render(context))
#     # Approach 3
#     context = {'user_list':user_list}
#     return render(request, 'myphotos/index.html', context)

@login_required()
def index(request):
    try:
        album_list = UserAlbum.objects.filter(user_id=request.user.id)
    except UserAlbum.DoesNotExist:
        album_list = ()
    return render(request, 'myphotos/albums.html', {'user':request.user, 'album_list':album_list})

@login_required()
def add_album(request):
    if request.method == 'POST':
        album = UserAlbum(
            user=request.user,
            name=request.POST['name'])
        album.save()
        return HttpResponseRedirect('/myphotos/%d/photos' % album.id)

@login_required()
def profile(request):
    # # try:
    # #     user = User.objects.get(pk=user_id)
    # # except User.DoesNotExist:
    # #     raise Http404
    # user = get_object_or_404(User, pk=user_id)
    return render(request, 'myphotos/profile.html', {'user':request.user})

@login_required()
def photos(request, album_id):
    # return HttpResponse("You are viewing photos in album %s" % album_id)
    album = get_object_or_404(UserAlbum, pk = album_id)
    try:
        photo_list = AlbumPhoto.objects.filter(album_id=album_id)
    except AlbumPhoto.DoesNotExist:
        photo_list = ()
    return render(request, 'myphotos/photos.html', {'user':request.user, 'album':album, 'photo_list':photo_list})

@login_required()
def add_photo(request, album_id):
    if request.method == 'POST':
        form = PhotoUploadForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                AlbumPhoto.objects.get(album_id=album_id, filename=request.FILES['imageFile'].name)
            except AlbumPhoto.DoesNotExist:
                instance = form.save(commit=False)
                instance.filename = request.FILES['imageFile'].name
                instance.album_id = album_id
                instance.save()
    return HttpResponseRedirect('/myphotos/%s/photos' % album_id)

@login_required()
def del_photo(request, album_id, photo_id):
    photo = get_object_or_404(AlbumPhoto, pk = photo_id)
    photo.delete()
    return HttpResponseRedirect('/myphotos/%s/photos' % album_id)

templates/base.html
<!doctype html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>

templates/myphotos/albums.html
<span style="float:right">
<a href="{% url 'auth_logout' %}">Logout</a>
</span>
<h1>Welcome {{ user }}</h1>
<br>
<hr>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'myphotos:add_album' %}" method="POST">
    Create an album::<input type="text" name="name">
    <input type="submit" value="Add">
    {% csrf_token %}
</form>
</p>
<ul>
    {% for album in album_list %}
    <li><a href="{% url 'myphotos:photos' album.id %}">{{ album.name }}</a></li>
    {% endfor %}
</ul>

templates/myphotos/index.html
{% if user_list %}
    <ul>
    {% for user in user_list %}
        <li><a href="/myphotos/{{ user.id }}/albums/">{{ user.username }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No users are available.</p>
{% endif %}

templates/myphotos/photos.html
<span style="float:right">
<a href="{% url 'auth_logout' %}">Logout</a>
</span>
<h1>You are viewing album '{{ album.name }}' by <a href="{% url 'myphotos:index' %}">{{ user }}</a></h1>
<a href="{% url 'myphotos:index' %}">&lt;&lt;Back</a>

<br>
<hr>
<form action="/myphotos/{{ album.id }}/photos/add/" method="post" enctype="multipart/form-data">
    <input name="imageFile" type="file" id="imageFile" />
    <input name="tags" type="text" id="tags">
    <input type="submit" id="submit" value="Submit File" />
    {% csrf_token %}
</form>
<ul>
    {% for photo in photo_list %}
        <hr>
        <li><a href="{{photo.imageFile.url}}">
                <img src="{{photo.imageFile.url}}" height=100>
                {{ photo.filename }}:{{ photo.tags }}
            </a> <a href="/myphotos/{{ album.id }}/photos/{{ photo.id }}/del/" style="float: right;">Delete</a>
        </li>
    {% endfor %}
</ul>

templates/myphotos/profile.html
{{ user }}